-- Enable Row Level Security
alter default privileges revoke execute on functions from public;

-- 1. Properties Table
create table public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null,
  location text not null,
  city text not null,
  type text not null check (type in ('House', 'Apartment', 'Plot')),
  status text not null check (status in ('Rent', 'Sale')),
  bedrooms int default 0,
  bathrooms numeric default 0,
  area numeric not null, -- sq ft
  images text[] default '{}',
  features text[] default '{}',
  user_id uuid references auth.users(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.properties enable row level security;

-- Policies for Properties
create policy "Public properties are viewable by everyone."
  on public.properties for select
  using ( true );

create policy "Users can insert their own properties."
  on public.properties for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own properties."
  on public.properties for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own properties."
  on public.properties for delete
  using ( auth.uid() = user_id );


-- 2. Favorites Table
create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  property_id bigint references public.properties(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, property_id)
);

alter table public.favorites enable row level security;

-- Policies for Favorites
create policy "Users can view their own favorites."
  on public.favorites for select
  using ( auth.uid() = user_id );

create policy "Users can add favorites."
  on public.favorites for insert
  with check ( auth.uid() = user_id );

create policy "Users can remove their own favorites."
  on public.favorites for delete
  using ( auth.uid() = user_id );
